El dataset contiene información de pasajeros del Titanic, incluyendo variables demográficas y del viaje, y el objetivo es predecir si un pasajero sobrevivió o no al hundimiento. La variable objetivo es survived, que aunque está como 0 y 1, representa clases (no sobrevivió / sobrevivió) y se trata como categórica. Las variables de entrada incluyen: pclass, que indica la clase del pasajero y se considera categórica ordinal; sex, variable categórica nominal que requiere limpieza de texto; age, variable numérica continua con valores faltantes que se imputan con la mediana; fare, que representa el precio del boleto, se limpia de texto y comas, se convierte a numérica y se imputan valores faltantes con la media; embarked, variable categórica nominal que indica el puerto de embarque, con valores faltantes e inconsistencias, se limpia, se imputan con la moda y se convierte a categórica; y booking_date, variable de tipo fecha con formatos inconsistentes que se normaliza a datetime para su correcto uso.

In [1]:
#Para esta actividad se importarán las siguientes librerías:
import pandas as pd
import numpy as np
from IPython.display import display

#Codigo para cargar el Dataset

url = 'https://raw.githubusercontent.com/DevLuis00/Data/refs/heads/main/titanic_sintetico_con_problemas.csv'
df_clean = pd.read_csv(url)
df = pd.read_csv(url)
df_clean.head()

,survived,pclass,sex,age,fare,embarked,booking_date,ticket
0,0,1,male,51.9,10.06,S,08/04/1912,PC 17599
1,1,3,male,29.1,6.08,S,1912-01-02,STON/O2. 3101282
2,0,3,male,22.2,16.65,s,1912-01-03,STON/O2. 3101282
3,0,3,female,56.3,3.62,S,01/09/1912,113803
4,0,3,male,9.7,19.27,C,02/10/1912,113803

In [2]:
print("\nRESUMEN GENERAL DEL DATASET\n")  
# Imprime un título en consola para indicar que comienza el resumen general del dataset.
# \n agrega un salto de línea antes y después del texto para mejor formato visual.

resumen = pd.DataFrame({
    "Filas": [df.shape[0]],  
    # df.shape[0] obtiene el número de filas del DataFrame.
    # Se coloca dentro de una lista porque el DataFrame espera valores tipo lista.

    "Columnas": [df.shape[1]],  
    # df.shape[1] obtiene el número de columnas del DataFrame.

    "Nulos Totales": [df.isnull().sum().sum()],  
    # df.isnull() convierte el DataFrame en booleanos (True donde hay nulos).
    # .sum() suma los nulos por columna.
    # El segundo .sum() suma todos los nulos del dataset completo.

    "Duplicados": [df.duplicated().sum()],  
    # df.duplicated() devuelve True en filas duplicadas.
    # .sum() cuenta cuántas filas están duplicadas.

    "Memoria (KB)": [round(df.memory_usage(deep=True).sum() / 1024, 2)]  
    # df.memory_usage(deep=True) calcula la memoria usada por cada columna.
    # .sum() suma la memoria total en bytes.
    # /1024 convierte a kilobytes.
    # round(..., 2) redondea a 2 decimales.
})

display(resumen)  
# Muestra el DataFrame resumen en formato tabular (útil en Jupyter Notebook).

print("\nTIPOS DE DATOS\n")  
# Imprime un título indicando que se mostrarán los tipos de datos.

display(df.dtypes)  
# df.dtypes muestra el tipo de dato de cada columna (int64, float64, object, etc.).

print("\nPRIMERAS FILAS DEL DATASET\n")  
# Imprime un título indicando que se mostrarán las primeras filas.

display(df.head())  
# df.head() muestra las primeras 5 filas del DataFrame por defecto.


print("\nAUDITORIA COMPLETA POR COLUMNA\n")  
# Imprime un título indicando que comienza una auditoría más detallada por columna.

resumen_lista = []  
# Se crea una lista vacía donde se almacenará la información detallada de cada columna.

for col in df.columns:  
    # Recorre cada nombre de columna en el DataFrame.

    col_data = df[col]  
    # Extrae los datos de la columna actual.

    tipos_serie = col_data.map(type)  
    # Aplica la función type a cada elemento de la columna.
    # Devuelve una serie con el tipo real de cada valor (ej: int, str, float).

    conteos = tipos_serie.value_counts()  
    # Cuenta cuántas veces aparece cada tipo de dato en la columna.

    conteos.index = conteos.index.map(str)  
    # Convierte los tipos (ej: <class 'int'>) a string para poder manejarlos mejor.

    porcentajes = tipos_serie.value_counts(normalize=True) * 100  
    # value_counts(normalize=True) calcula la proporción en vez del conteo.
    # *100 convierte la proporción a porcentaje.

    porcentajes.index = porcentajes.index.map(str)  
    # Convierte los índices de tipos también a string para que coincidan con conteos.

    for tipo_str in conteos.index:  
        # Recorre cada tipo de dato detectado en la columna.

        resumen_lista.append({
            "Columna": col,  
            # Nombre de la columna analizada.

            "Tipo Detectado": tipo_str,  
            # Tipo de dato encontrado (como string).

            "Cantidad": conteos.loc[tipo_str],  
            # Cantidad de veces que aparece ese tipo en la columna.

            "Porcentaje": f"{porcentajes.loc[tipo_str]:.2f}%"  
            # Porcentaje formateado con 2 decimales y símbolo %.
        })

df_revelador = pd.DataFrame(resumen_lista)  
# Convierte la lista de diccionarios en un nuevo DataFrame estructurado.

display(df_revelador)  
# Muestra el DataFrame final con la auditoría completa por columna.

RESUMEN GENERAL DEL DATASET

   Filas  Columnas  Nulos Totales  Duplicados  Memoria (KB)
0    630         8             72           0        208.45

TIPOS DE DATOS

survived          int64
pclass            int64
sex              object
age             float64
fare             object
embarked         object
booking_date     object
ticket           object
dtype: object

PRIMERAS FILAS DEL DATASET

,survived,pclass,sex,age,fare,embarked,booking_date,ticket
0,0,1,male,51.9,10.06,S,08/04/1912,PC 17599
1,1,3,male,29.1,6.08,S,1912-01-02,STON/O2. 3101282
2,0,3,male,22.2,16.65,s,1912-01-03,STON/O2. 3101282
3,0,3,female,56.3,3.62,S,01/09/1912,113803
4,0,3,male,9.7,19.27,C,02/10/1912,113803

AUDITORIA COMPLETA POR COLUMNA

        Columna   Tipo Detectado  Cantidad Porcentaje
0      survived    <class 'int'>       630    100.00%
1        pclass    <class 'int'>       630    100.00%
2           sex    <class 'str'>       630    100.00%
3           age  <class 'float'>       630    100.00%
4          fare    <class 'str'>       623     98.89%
5          fare  <class 'float'>         7      1.11%
6      embarked    <class 'str'>       609     96.67%
7      embarked  <class 'float'>        21      3.33%
8  booking_date    <class 'str'>       630    100.00%
9        ticket    <class 'str'>       630    100.00%

# **Tratamiento de la columna survived**

In [3]:
df_clean['survived'] = df_clean['survived'].map({
    0: 'No sobrevivio',
    1: 'Sobrevivio'
})
# df_clean['survived'] selecciona la columna 'survived' del DataFrame limpio.
# .map({...}) reemplaza los valores numéricos usando un diccionario.
# 0 se transforma en 'No sobrevivio'.
# 1 se transforma en 'Sobrevivio'.
# Es decir, convierte una variable binaria numérica en una variable categórica legible.

df_clean['survived'] = (
    df_clean['survived']
    .astype('category')  
)
# .astype('category') convierte la columna al tipo categórico de pandas.
# Esto es más eficiente en memoria que usar strings normales.
# Además permite que pandas trate la variable como una categoría formal
# (útil para análisis estadístico, modelos y visualizaciones).

# **Tratamiento de la columna Pclass**

In [4]:
df_clean['pclass'] = (
    df_clean['pclass']
    .astype(str)        # Convierte todos los valores a tipo string (texto)
    .str.strip()        # Elimina espacios en blanco al inicio y al final
    .astype('category') # Convierte la columna a tipo categórico
)

# **Tratamiento de la columna sex**

In [5]:
df_clean['sex'] = (
    df_clean['sex']
    .str.strip()        # Elimina espacios en blanco al inicio y al final
    .str.upper()        # Convierte todo el texto a mayúsculas
    .astype('category') # Convierte la columna a tipo categórico
)

# **Tratamiento de la columna age**

In [6]:
df_clean['age'].isnull().sum()

np.int64(44)

In [7]:
(df['age'] < 0).sum()

np.int64(9)

In [8]:
df_clean['age'] = (
    df_clean['age']
    .abs()                         # Convierte todos los valores a su valor absoluto
    .fillna(df_clean['age'].mean()) # Reemplaza los valores nulos por la media de la edad
    .astype(int)                   # Convierte los valores a enteros
)

In [9]:
df_clean['age'].isnull().sum()

np.int64(0)

In [10]:
(df['age'] < 0).sum()

np.int64(9)

In [11]:
df_clean.head()

,survived,pclass,sex,age,fare,embarked,booking_date,ticket
0,No sobrevivio,1,MALE,51,10.06,S,08/04/1912,PC 17599
1,Sobrevivio,3,MALE,29,6.08,S,1912-01-02,STON/O2. 3101282
2,No sobrevivio,3,MALE,22,16.65,s,1912-01-03,STON/O2. 3101282
3,No sobrevivio,3,FEMALE,56,3.62,S,01/09/1912,113803
4,No sobrevivio,3,MALE,9,19.27,C,02/10/1912,113803

# **Tratamiento de la columna fare**

In [12]:
df_clean['fare'] = (
    df_clean['fare']
    .astype(str)                      # Convierte todos los valores a texto
    .str.strip()                      # Elimina espacios al inicio y al final
    .str.replace(',', '', regex=False) # Elimina comas (ej: "1,200" → "1200")
)

df_clean['fare'] = pd.to_numeric(
    df_clean['fare'],
    errors='coerce'                   # Valores no válidos se convierten en NaN
)

df_clean['fare'] = (
    df_clean['fare']
    .fillna(df_clean['fare'].mean())  # Reemplaza los valores nulos por la media
)

# **Tratamiento de la columna embarked**

In [13]:
df_clean['embarked'] = (
    df_clean['embarked']
    .str.strip()      # Elimina espacios al inicio y al final
    .str.upper()      # Convierte todo a mayúsculas
)

df_clean['embarked'].fillna(
    df_clean['embarked'].mode()[0],   # Reemplaza NaN con la moda (valor más frecuente)
    inplace=True
)

df_clean['embarked'] = df_clean['embarked'].map({
    'S': 'Southampton',
    'C': 'Cherbourg',
    'Q': 'Queenstown'
})  # Reemplaza códigos por nombres completos del puerto

df_clean['embarked'] = (
    df_clean['embarked']
    .str.upper()      # Convierte los nombres a mayúsculas
    .astype('category')  # Convierte la columna a tipo categórico
)

/tmp/ipykernel_9111/2130471387.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean['embarked'].fillna(

# **Tratamiento de la columna booking_date**

In [14]:
df_clean['booking_date'] = pd.to_datetime(
    df_clean['booking_date'],      # Selecciona la columna con las fechas en formato texto
    format='mixed',                # Permite distintos formatos de fecha en la misma columna
    dayfirst=True                  # Indica que el día viene antes que el mes (ej: 25/12/2023)
)  # Convierte la columna a tipo datetime

# **Tratamiento de la columna ticket**

In [15]:
df_clean['ticket'] = (
    df_clean['ticket']
    .astype(str)        # Convertir los valores a texto
    .str.strip()        # Eliminar espacios al inicio y al final
    .str.upper()        # Convertir todo a mayúsculas
    .astype('category') # Convertir la columna a tipo categórico
)

# **Resultados**

In [16]:
print("=== COMPARACION DE COLUMNAS, FILAS, NAN ===")  
# Título para la comparación general

comparacion = pd.DataFrame({
    "Filas": [df.shape[0], df_clean.shape[0]],  
    # Número de filas del dataset original y limpio

    "Columnas": [df.shape[1], df_clean.shape[1]],  
    # Número de columnas en ambos datasets

    "Nulos": [
        df.isnull().sum().sum(),  
        df_clean.isnull().sum().sum()
    ],  
    # Total de valores NaN en cada dataset

    "Duplicados": [
        df.duplicated().sum(),  
        df_clean.duplicated().sum()
    ],  
    # Total de filas duplicadas

    "Memoria (KB)": [
        round(df.memory_usage(deep=True).sum() / 1024, 2),  
        round(df_clean.memory_usage(deep=True).sum() / 1024, 2)
    ]  
    # Memoria usada por cada dataset en KB
}, index=["Original", "Limpio"])  
# Se agregan etiquetas a las filas para identificar cada dataset

display(comparacion)  
# Muestra la tabla comparativa

print("=== TIPOS DE DATOS ===")  
# Título para la comparación de tipos

tipos = pd.DataFrame({
    "Tipo Original": df.dtypes,  
    # Tipos de datos del dataset original
    "Tipo Limpio": df_clean.dtypes  
    # Tipos de datos después de la limpieza
})

display(tipos)  
# Muestra la comparación de tipos de datos

print("=== PRIMERAS FILAS DATASET ORIGINAL ===")
display(df.head())  
# Muestra las primeras 5 filas del dataset original

print("=== PRIMERAS FILAS DATASET LIMPIO ===")
display(df_clean.head())  
# Muestra las primeras 5 filas del dataset limpio

print("=== DATASET ORIGINAL ===")
print(df.describe())  
# Estadísticas descriptivas del dataset original (numéricas)

print("\n=== DATASET LIMPIO ===")
print(df_clean.describe())  
# Estadísticas descriptivas del dataset limpio

=== COMPARACION DE COLUMNAS, FILAS, NAN ===

          Filas  Columnas  Nulos  Duplicados  Memoria (KB)
Original    630         8     72           0        208.45
Limpio      630         8      0           0         19.76

=== TIPOS DE DATOS ===

             Tipo Original     Tipo Limpio
survived             int64        category
pclass               int64        category
sex                 object        category
age                float64           int64
fare                object         float64
embarked            object        category
booking_date        object  datetime64[ns]
ticket              object        category

=== PRIMERAS FILAS DATASET ORIGINAL ===

,survived,pclass,sex,age,fare,embarked,booking_date,ticket
0,0,1,male,51.9,10.06,S,08/04/1912,PC 17599
1,1,3,male,29.1,6.08,S,1912-01-02,STON/O2. 3101282
2,0,3,male,22.2,16.65,s,1912-01-03,STON/O2. 3101282
3,0,3,female,56.3,3.62,S,01/09/1912,113803
4,0,3,male,9.7,19.27,C,02/10/1912,113803

=== PRIMERAS FILAS DATASET LIMPIO ===

,survived,pclass,sex,age,fare,embarked,booking_date,ticket
0,No sobrevivio,1,MALE,51,10.06,SOUTHAMPTON,1912-04-08,PC 17599
1,Sobrevivio,3,MALE,29,6.08,SOUTHAMPTON,1912-01-02,STON/O2. 3101282
2,No sobrevivio,3,MALE,22,16.65,SOUTHAMPTON,1912-01-03,STON/O2. 3101282
3,No sobrevivio,3,FEMALE,56,3.62,SOUTHAMPTON,1912-09-01,113803
4,No sobrevivio,3,MALE,9,19.27,CHERBOURG,1912-10-02,113803

=== DATASET ORIGINAL ===
         survived      pclass         age
count  630.000000  630.000000  586.000000
mean     0.520635    2.271429   31.509386
std      0.499971    0.861272   14.116806
min      0.000000    1.000000  -10.500000
25%      0.000000    1.000000   21.825000
50%      1.000000    3.000000   31.600000
75%      1.000000    3.000000   40.575000
max      1.000000    3.000000   66.400000

=== DATASET LIMPIO ===
              age         fare                   booking_date
count  630.000000   630.000000                            630
mean    31.196825   230.668668  1912-09-08 22:19:25.714285824
min      0.000000     1.330000            1912-01-02 00:00:00
25%     22.000000     9.645000            1912-04-28 00:00:00
50%     31.000000    15.500000            1912-08-04 00:00:00
75%     39.000000    27.175000            1912-12-31 06:00:00
max     66.000000  8200.500000            1913-09-18 00:00:00
std     13.265636  1287.909153                            NaN