In [3]:
import pandas as pd
import numpy as np
from IPython.display import display

#Codigo para cargar el Dataset

url = 'https://raw.githubusercontent.com/hmedrano1979/ITC/refs/heads/main/dataset_clientes_ventas_con_problemas.csv'
df = pd.read_csv(url)
df_clean = pd.read_csv(url) 
df.head()

,id,nombre_cliente,ciudad,monto_compra,fecha_compra,ticket,sexo
0,1,Juana,barranquilla,4500,01/02/2023,PC 17599,MALE
1,2,Pedro,bquilla,"2.500,75",10-04-2023 08:30:00,PC 17599,Female
2,3,JUAN,cartagena de indias,NaN,2023/03/05,PC 17599,female
3,4,Juana,Barranquilla,"2.500,75",2023-01-01,PC 17599,MALE
4,5,María,BARRANQUILLA,4500,10-04-2023 08:30:00,S.O.C. 14879,female

In [4]:
print("\nRESUMEN GENERAL DEL DATASET\n")

resumen = pd.DataFrame({
    "Filas": [df.shape[0]],
    "Columnas": [df.shape[1]],
    "Nulos Totales": [df.isnull().sum().sum()],
    "Duplicados": [df.duplicated().sum()],
    "Memoria (KB)": [round(df.memory_usage(deep=True).sum() / 1024, 2)]
})

display(resumen)

print("\nTIPOS DE DATOS\n")
display(df.dtypes)

print("\nPRIMERAS FILAS DEL DATASET\n")
display(df.head())


print("\nAUDITORIA COMPLETA POR COLUMNA\n")

resumen_lista = []

for col in df.columns:

    col_data = df[col]
    tipos_serie = col_data.map(type)

    conteos = tipos_serie.value_counts()
    conteos.index = conteos.index.map(str)

    porcentajes = tipos_serie.value_counts(normalize=True) * 100
    porcentajes.index = porcentajes.index.map(str)

    for tipo_str in conteos.index:
        resumen_lista.append({
            "Columna": col,
            "Tipo Detectado": tipo_str,
            "Cantidad": conteos.loc[tipo_str],
            "Porcentaje": f"{porcentajes.loc[tipo_str]:.2f}%"
        })

df_revelador = pd.DataFrame(resumen_lista)
display(df_revelador)

RESUMEN GENERAL DEL DATASET

   Filas  Columnas  Nulos Totales  Duplicados  Memoria (KB)
0    630         7            158          30        250.24

TIPOS DE DATOS

id                 int64
nombre_cliente    object
ciudad            object
monto_compra      object
fecha_compra      object
ticket            object
sexo              object
dtype: object

PRIMERAS FILAS DEL DATASET

,id,nombre_cliente,ciudad,monto_compra,fecha_compra,ticket,sexo
0,1,Juana,barranquilla,4500,01/02/2023,PC 17599,MALE
1,2,Pedro,bquilla,"2.500,75",10-04-2023 08:30:00,PC 17599,Female
2,3,JUAN,cartagena de indias,NaN,2023/03/05,PC 17599,female
3,4,Juana,Barranquilla,"2.500,75",2023-01-01,PC 17599,MALE
4,5,María,BARRANQUILLA,4500,10-04-2023 08:30:00,S.O.C. 14879,female

AUDITORIA COMPLETA POR COLUMNA

          Columna   Tipo Detectado  Cantidad Porcentaje
0              id    <class 'int'>       630    100.00%
1  nombre_cliente    <class 'str'>       630    100.00%
2          ciudad    <class 'str'>       603     95.71%
3          ciudad  <class 'float'>        27      4.29%
4    monto_compra    <class 'str'>       499     79.21%
5    monto_compra  <class 'float'>       131     20.79%
6    fecha_compra    <class 'str'>       630    100.00%
7          ticket    <class 'str'>       630    100.00%
8            sexo    <class 'str'>       630    100.00%